name: Merge JSON Files Only (Testing for Mapping Errors)

on:
  workflow_dispatch:

jobs:
  merge_json_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout VulnBagel Repository
        uses: actions/checkout@v4
        with:
          repository: SecurityBagel/VulnBagel
          path: ./VulnBagel

      - name: Checkout Vulnrichment Repository
        uses: actions/checkout@v4
        with:
          repository: cisagov/vulnrichment
          path: ./Vulnrichment

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Merge JSON Files (Testing without Push)
        run: |
          import os
          import json

          # Set paths
          json_root_dir = './Vulnrichment'
          output_file = './VulnBagel/merged_cve_data_test.json'

          # Combine JSON data with a limit
          combined_data = []
          file_limit = 10
          processed_files = 0

          for subdir, _, files in os.walk(json_root_dir):
              for file in files:
                  if file.endswith('.json') and processed_files < file_limit:
                      file_path = os.path.join(subdir, file)
                      with open(file_path, 'r') as f:
                          data = json.load(f)
                          combined_data.append(data)
                          processed_files += 1

          # Save combined data to output file
          with open(output_file, 'w') as f_out:
              json.dump(combined_data, f_out)

      - name: Commit JSON to VulnBagel (No Push)
        working-directory: ./VulnBagel
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add merged_cve_data_test.json
          git commit -m "Add merged JSON file (limited test)" || echo "No changes to commit"
