name: Merge and Push JSON Files (Testing for Duplicated Mapping Key Issues)

on:
  workflow_dispatch:

jobs:
  merge_json_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout VulnBagel Repository
        uses: actions/checkout@v4
        with:
          repository: SecurityBagel/VulnBagel
          path: ./VulnBagel

      - name: Checkout Vulnrichment Repository
        uses: actions/checkout@v4
        with:
          repository: cisagov/vulnrichment
          path: ./Vulnrichment

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create and Run Python Script to Merge JSON Files
        run: |
          echo "import os" > merge_json_files.py
          echo "import json" >> merge_json_files.py
          echo "json_root_dir = './Vulnrichment'" >> merge_json_files.py
          echo "output_file = './VulnBagel/merged_cve_data_test.json'" >> merge_json_files.py
          echo "combined_data = []" >> merge_json_files.py
          echo "file_limit = 10" >> merge_json_files.py
          echo "processed_files = 0" >> merge_json_files.py
          echo "for subdir, _, files in os.walk(json_root_dir):" >> merge_json_files.py
          echo "    for file in files:" >> merge_json_files.py
          echo "        if file.endswith('.json') and processed_files < file_limit:" >> merge_json_files.py
          echo "            file_path = os.path.join(subdir, file)" >> merge_json_files.py
          echo "            with open(file_path, 'r') as f:" >> merge_json_files.py
          echo "                data = json.load(f)" >> merge_json_files.py
          echo "                combined_data.append(data)" >> merge_json_files.py
          echo "                processed_files += 1" >> merge_json_files.py
          echo "with open(output_file, 'w') as f_out:" >> merge_json_files.py
          echo "    json.dump(combined_data, f_out)" >> merge_json_files.py
          python merge_json_files.py

      - name: Commit and Push Merged JSON to VulnBagel
        working-directory: ./VulnBagel
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add merged_cve_data_test.json
          git commit -m "Add merged JSON file (limited test)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT_VULNBAGEL }}@github.com/SecurityBagel/VulnBagel.git HEAD:test-branch

