name: Merge and Push JSON Files (Limited to 10 Files for Testing)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC (optional)

jobs:
  merge_json_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout VulnBagel Repository
        uses: actions/checkout@v3
        with:
          repository: SecurityBagel/VulnBagel  # Ensure your GitHub username and repository name are correct
          path: ./VulnBagel

      - name: Checkout Vulnrichment Repository
        uses: actions/checkout@v3
        with:
          repository: cisagov/vulnrichment
          path: ./Vulnrichment

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Merge JSON Files (Testing with Limited Files)
        run: |
          import os
          import json

          # Set paths
          json_root_dir = './Vulnrichment'  # Where JSON files are located in Vulnrichment
          output_file = './VulnBagel/merged_cve_data_test.json'  # Output file location in VulnBagel

          # Combine JSON data with a limit
          combined_data = []
          file_limit = 10  # Process only the first 10 files for testing
          processed_files = 0

          for subdir, _, files in os.walk(json_root_dir):
              for file in files:
                  if file.endswith('.json') and processed_files < file_limit:
                      file_path = os.path.join(subdir, file)
                      with open(file_path, 'r') as f:
                          data = json.load(f)
                          combined_data.append(data)
                          processed_files += 1

          # Save combined data to output file
          with open(output_file, 'w') as f_out:
              json.dump(combined_data, f_out)

      - name: Commit and Push Merged JSON to VulnBagel
        working-directory: ./VulnBagel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_VULNBAGEL }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add merged_cve_data_test.json
          git commit -m "Add merged JSON file (limited test)"
          git push



